/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Libellus;

import java.awt.CardLayout;
import Database.DatabaseCheck;

/**
 *
 * @author Brina
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        MainPanel = new javax.swing.JPanel();
        WelcomePanel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        eLogIn = new javax.swing.JButton();
        mLogIn = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        EmployeeLogInPanel = new javax.swing.JPanel();
        eUsernameField = new javax.swing.JTextField();
        ePasswordField = new javax.swing.JTextField();
        eLoginTitle = new javax.swing.JLabel();
        eUsernameLabel = new javax.swing.JLabel();
        ePasswordLabel = new javax.swing.JLabel();
        eLoginButton = new javax.swing.JButton();
        eGoBackButton = new javax.swing.JButton();
        MemberLogInPanel = new javax.swing.JPanel();
        mLoginTitle = new javax.swing.JLabel();
        mUsernameLabel = new javax.swing.JLabel();
        mPasswordLabel = new javax.swing.JLabel();
        mUsernameField = new javax.swing.JTextField();
        mPasswordField = new javax.swing.JTextField();
        mLoginButton = new javax.swing.JButton();
        mGoBackButton = new javax.swing.JButton();
        EmployeeHomePanel = new javax.swing.JPanel();
        eHomeLabel = new javax.swing.JLabel();
        eLogOutButton = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        eMembersButton = new javax.swing.JButton();
        eBooksButton = new javax.swing.JButton();
        eCheckOutButton = new javax.swing.JButton();
        MemberHomePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mLogOutButton = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        mAccountButton = new javax.swing.JButton();
        mCanaryButton = new javax.swing.JButton();
        MemberManagementPanel = new javax.swing.JPanel();
        eMMGoBackButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        BookManagementPanel = new javax.swing.JPanel();
        eBMGoBackButton = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        MainPanel.setMaximumSize(new java.awt.Dimension(800, 600));
        MainPanel.setMinimumSize(new java.awt.Dimension(800, 600));
        MainPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        MainPanel.setLayout(new java.awt.CardLayout());

        WelcomePanel.setMaximumSize(new java.awt.Dimension(800, 600));
        WelcomePanel.setMinimumSize(new java.awt.Dimension(800, 600));

        title.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        title.setText("Welcome to Libellus!");

        eLogIn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        eLogIn.setText("Employee Log In");
        eLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eLogInActionPerformed(evt);
            }
        });

        mLogIn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mLogIn.setText("Member Log In");
        mLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mLogInActionPerformed(evt);
            }
        });

        exit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Sample Picture.png"))); // NOI18N

        jButton1.setText("Database Check");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDatabaseCheckAction(evt);
            }
        });

        javax.swing.GroupLayout WelcomePanelLayout = new javax.swing.GroupLayout(WelcomePanel);
        WelcomePanel.setLayout(WelcomePanelLayout);
        WelcomePanelLayout.setHorizontalGroup(
            WelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomePanelLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(eLogIn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mLogIn)
                .addGap(131, 131, 131))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WelcomePanelLayout.createSequentialGroup()
                .addGroup(WelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WelcomePanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logo)
                        .addGap(204, 204, 204))
                    .addGroup(WelcomePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(exit)
                .addGap(19, 19, 19))
            .addGroup(WelcomePanelLayout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(title)
                .addContainerGap(164, Short.MAX_VALUE))
        );
        WelcomePanelLayout.setVerticalGroup(
            WelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WelcomePanelLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(title)
                .addGap(125, 125, 125)
                .addGroup(WelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eLogIn)
                    .addComponent(mLogIn))
                .addGroup(WelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WelcomePanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(logo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WelcomePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exit)
                        .addGap(39, 39, 39))))
        );

        MainPanel.add(WelcomePanel, "WelcomePanel");
        WelcomePanel.getAccessibleContext().setAccessibleName("");

        EmployeeLogInPanel.setMaximumSize(new java.awt.Dimension(800, 600));
        EmployeeLogInPanel.setMinimumSize(new java.awt.Dimension(800, 600));
        EmployeeLogInPanel.setPreferredSize(new java.awt.Dimension(800, 600));

        eLoginTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        eLoginTitle.setText("Employee Log In");

        eUsernameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        eUsernameLabel.setText("Username:");

        ePasswordLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ePasswordLabel.setText("Password:");

        eLoginButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        eLoginButton.setText("Log In");
        eLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eLoginButtonActionPerformed(evt);
            }
        });

        eGoBackButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        eGoBackButton.setText("Go Back");
        eGoBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eGoBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EmployeeLogInPanelLayout = new javax.swing.GroupLayout(EmployeeLogInPanel);
        EmployeeLogInPanel.setLayout(EmployeeLogInPanelLayout);
        EmployeeLogInPanelLayout.setHorizontalGroup(
            EmployeeLogInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeLogInPanelLayout.createSequentialGroup()
                .addGroup(EmployeeLogInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EmployeeLogInPanelLayout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addGroup(EmployeeLogInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(EmployeeLogInPanelLayout.createSequentialGroup()
                                .addGroup(EmployeeLogInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(eUsernameLabel)
                                    .addComponent(ePasswordLabel))
                                .addGap(18, 18, 18)
                                .addGroup(EmployeeLogInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(eUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ePasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(EmployeeLogInPanelLayout.createSequentialGroup()
                                .addComponent(eLoginButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(eGoBackButton))))
                    .addGroup(EmployeeLogInPanelLayout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addComponent(eLoginTitle)))
                .addContainerGap(262, Short.MAX_VALUE))
        );
        EmployeeLogInPanelLayout.setVerticalGroup(
            EmployeeLogInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeLogInPanelLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(eLoginTitle)
                .addGap(55, 55, 55)
                .addGroup(EmployeeLogInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eUsernameLabel)
                    .addComponent(eUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(EmployeeLogInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ePasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ePasswordLabel))
                .addGap(38, 38, 38)
                .addGroup(EmployeeLogInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eLoginButton)
                    .addComponent(eGoBackButton))
                .addContainerGap(284, Short.MAX_VALUE))
        );

        MainPanel.add(EmployeeLogInPanel, "EmployeeLogInPanel");

        MemberLogInPanel.setMaximumSize(new java.awt.Dimension(800, 600));
        MemberLogInPanel.setMinimumSize(new java.awt.Dimension(800, 600));
        MemberLogInPanel.setPreferredSize(new java.awt.Dimension(800, 600));

        mLoginTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mLoginTitle.setText("Member Log In");

        mUsernameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mUsernameLabel.setText("Username:");

        mPasswordLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mPasswordLabel.setText("Password:");

        mLoginButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mLoginButton.setText("Log In");
        mLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mLoginButtonActionPerformed(evt);
            }
        });

        mGoBackButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mGoBackButton.setText("Go Back");
        mGoBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mGoBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MemberLogInPanelLayout = new javax.swing.GroupLayout(MemberLogInPanel);
        MemberLogInPanel.setLayout(MemberLogInPanelLayout);
        MemberLogInPanelLayout.setHorizontalGroup(
            MemberLogInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MemberLogInPanelLayout.createSequentialGroup()
                .addGroup(MemberLogInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MemberLogInPanelLayout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addGroup(MemberLogInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MemberLogInPanelLayout.createSequentialGroup()
                                .addComponent(mPasswordLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(MemberLogInPanelLayout.createSequentialGroup()
                                .addComponent(mUsernameLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(MemberLogInPanelLayout.createSequentialGroup()
                                .addComponent(mLoginButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mGoBackButton))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MemberLogInPanelLayout.createSequentialGroup()
                        .addGap(379, 379, 379)
                        .addComponent(mUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(262, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MemberLogInPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mLoginTitle)
                .addGap(286, 286, 286))
        );
        MemberLogInPanelLayout.setVerticalGroup(
            MemberLogInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MemberLogInPanelLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(mLoginTitle)
                .addGap(55, 55, 55)
                .addGroup(MemberLogInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mUsernameLabel)
                    .addComponent(mUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(MemberLogInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mPasswordLabel)
                    .addComponent(mPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(MemberLogInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mLoginButton)
                    .addComponent(mGoBackButton))
                .addContainerGap(284, Short.MAX_VALUE))
        );

        MainPanel.add(MemberLogInPanel, "MemberLogInPanel");

        eHomeLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        eHomeLabel.setText("Home");

        eLogOutButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        eLogOutButton.setText("Log Out");
        eLogOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eLogOutButtonActionPerformed(evt);
            }
        });

        jTextField1.setText("Search for a book");

        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton1.setText("By Name");

        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton2.setText("By Author");

        jRadioButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton3.setText("By ISBN");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Sample Picture.png"))); // NOI18N

        eMembersButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        eMembersButton.setText("Members");
        eMembersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eMembersButtonActionPerformed(evt);
            }
        });

        eBooksButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        eBooksButton.setText("Books");
        eBooksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eBooksButtonActionPerformed(evt);
            }
        });

        eCheckOutButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        eCheckOutButton.setText("Check Out");
        eCheckOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eCheckOutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EmployeeHomePanelLayout = new javax.swing.GroupLayout(EmployeeHomePanel);
        EmployeeHomePanel.setLayout(EmployeeHomePanelLayout);
        EmployeeHomePanelLayout.setHorizontalGroup(
            EmployeeHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeHomePanelLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(EmployeeHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EmployeeHomePanelLayout.createSequentialGroup()
                        .addComponent(eCheckOutButton)
                        .addGap(76, 76, 76)
                        .addComponent(jRadioButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(EmployeeHomePanelLayout.createSequentialGroup()
                        .addGroup(EmployeeHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eBooksButton)
                            .addComponent(eMembersButton))
                        .addGap(223, 223, 223)
                        .addComponent(eHomeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                        .addComponent(eLogOutButton)
                        .addGap(75, 75, 75))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmployeeHomePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(EmployeeHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmployeeHomePanelLayout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(175, 175, 175))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmployeeHomePanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(253, 253, 253))))
        );
        EmployeeHomePanelLayout.setVerticalGroup(
            EmployeeHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeHomePanelLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(EmployeeHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eHomeLabel)
                    .addComponent(eLogOutButton)
                    .addComponent(eMembersButton))
                .addGap(33, 33, 33)
                .addComponent(eBooksButton)
                .addGroup(EmployeeHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EmployeeHomePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(EmployeeHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton3)))
                    .addGroup(EmployeeHomePanelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(eCheckOutButton)))
                .addGap(41, 41, 41)
                .addComponent(jLabel2)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        MainPanel.add(EmployeeHomePanel, "EmployeeHomePanel");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Home");

        mLogOutButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mLogOutButton.setText("Log Out");
        mLogOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mLogOutButtonActionPerformed(evt);
            }
        });

        jTextField2.setText("Search for a book");

        jRadioButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton4.setText("By Name");

        jRadioButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton5.setText("By Author");

        jRadioButton6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton6.setText("By ISBN");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        mAccountButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mAccountButton.setText("Account Info");
        mAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAccountButtonActionPerformed(evt);
            }
        });

        mCanaryButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mCanaryButton.setText("Canary");

        javax.swing.GroupLayout MemberHomePanelLayout = new javax.swing.GroupLayout(MemberHomePanel);
        MemberHomePanel.setLayout(MemberHomePanelLayout);
        MemberHomePanelLayout.setHorizontalGroup(
            MemberHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MemberHomePanelLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(MemberHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MemberHomePanelLayout.createSequentialGroup()
                        .addComponent(mAccountButton)
                        .addGap(141, 141, 141)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mLogOutButton)
                        .addGap(75, 75, 75))
                    .addGroup(MemberHomePanelLayout.createSequentialGroup()
                        .addComponent(mCanaryButton)
                        .addGap(142, 142, 142)
                        .addGroup(MemberHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MemberHomePanelLayout.createSequentialGroup()
                                .addComponent(jRadioButton4)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton5)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton6))
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(159, Short.MAX_VALUE))))
        );
        MemberHomePanelLayout.setVerticalGroup(
            MemberHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MemberHomePanelLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(MemberHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(mLogOutButton)
                    .addComponent(mAccountButton))
                .addGroup(MemberHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MemberHomePanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(mCanaryButton))
                    .addGroup(MemberHomePanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(MemberHomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton6))
                .addContainerGap(358, Short.MAX_VALUE))
        );

        MainPanel.add(MemberHomePanel, "MemberHomePanel");

        eMMGoBackButton.setText("Go Back");
        eMMGoBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eMMGoBackButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Create New Member");

        jButton3.setText("Modify Existing Member");

        jButton4.setText("Pay Overdue Fees");

        javax.swing.GroupLayout MemberManagementPanelLayout = new javax.swing.GroupLayout(MemberManagementPanel);
        MemberManagementPanel.setLayout(MemberManagementPanelLayout);
        MemberManagementPanelLayout.setHorizontalGroup(
            MemberManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MemberManagementPanelLayout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(MemberManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MemberManagementPanelLayout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(MemberManagementPanelLayout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(MemberManagementPanelLayout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 326, Short.MAX_VALUE)
                        .addComponent(eMMGoBackButton)
                        .addGap(119, 119, 119))))
        );
        MemberManagementPanelLayout.setVerticalGroup(
            MemberManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MemberManagementPanelLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(MemberManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eMMGoBackButton)
                    .addComponent(jButton2))
                .addGap(55, 55, 55)
                .addComponent(jButton3)
                .addGap(58, 58, 58)
                .addComponent(jButton4)
                .addContainerGap(347, Short.MAX_VALUE))
        );

        MainPanel.add(MemberManagementPanel, "MemberManagementPanel");

        eBMGoBackButton.setText("Go Back");
        eBMGoBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eBMGoBackButtonActionPerformed(evt);
            }
        });

        jButton5.setText("Add Books");

        jButton6.setText("Remove Books");

        jButton7.setText("Requested Books");

        jButton8.setText("Orders");

        javax.swing.GroupLayout BookManagementPanelLayout = new javax.swing.GroupLayout(BookManagementPanel);
        BookManagementPanel.setLayout(BookManagementPanelLayout);
        BookManagementPanelLayout.setHorizontalGroup(
            BookManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookManagementPanelLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addGroup(BookManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BookManagementPanelLayout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(BookManagementPanelLayout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 368, Short.MAX_VALUE)
                        .addComponent(eBMGoBackButton)
                        .addGap(121, 121, 121))
                    .addGroup(BookManagementPanelLayout.createSequentialGroup()
                        .addGroup(BookManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton8)
                            .addComponent(jButton7))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        BookManagementPanelLayout.setVerticalGroup(
            BookManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookManagementPanelLayout.createSequentialGroup()
                .addGroup(BookManagementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BookManagementPanelLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(eBMGoBackButton))
                    .addGroup(BookManagementPanelLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jButton5)))
                .addGap(39, 39, 39)
                .addComponent(jButton6)
                .addGap(49, 49, 49)
                .addComponent(jButton7)
                .addGap(47, 47, 47)
                .addComponent(jButton8)
                .addContainerGap(294, Short.MAX_VALUE))
        );

        MainPanel.add(BookManagementPanel, "BookManagementPanel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eLogInActionPerformed
        CardLayout card = (CardLayout)MainPanel.getLayout();
        card.show(MainPanel, "EmployeeLogInPanel");
    }//GEN-LAST:event_eLogInActionPerformed

    private void mLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mLogInActionPerformed
        CardLayout card = (CardLayout)MainPanel.getLayout();
        card.show(MainPanel, "MemberLogInPanel");
    }//GEN-LAST:event_mLogInActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void eLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eLoginButtonActionPerformed
        CardLayout card = (CardLayout)MainPanel.getLayout();
        card.show(MainPanel, "EmployeeHomePanel");
    }//GEN-LAST:event_eLoginButtonActionPerformed

    private void mGoBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mGoBackButtonActionPerformed
        CardLayout card = (CardLayout)MainPanel.getLayout();
        card.show(MainPanel, "WelcomePanel");
    }//GEN-LAST:event_mGoBackButtonActionPerformed

    private void eGoBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eGoBackButtonActionPerformed
        CardLayout card = (CardLayout)MainPanel.getLayout();
        card.show(MainPanel, "WelcomePanel");
    }//GEN-LAST:event_eGoBackButtonActionPerformed

    private void mLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mLoginButtonActionPerformed
        CardLayout card = (CardLayout)MainPanel.getLayout();
        card.show(MainPanel, "MemberHomePanel");
    }//GEN-LAST:event_mLoginButtonActionPerformed

    private void eCheckOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eCheckOutButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eCheckOutButtonActionPerformed

    private void eLogOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eLogOutButtonActionPerformed
        CardLayout card = (CardLayout)MainPanel.getLayout();
        card.show(MainPanel, "WelcomePanel");
    }//GEN-LAST:event_eLogOutButtonActionPerformed

    private void eMembersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eMembersButtonActionPerformed
        CardLayout card = (CardLayout)MainPanel.getLayout();
        card.show(MainPanel, "MemberManagementPanel");
    }//GEN-LAST:event_eMembersButtonActionPerformed

    private void eBooksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eBooksButtonActionPerformed
        CardLayout card = (CardLayout)MainPanel.getLayout();
        card.show(MainPanel, "BookManagementPanel");
    }//GEN-LAST:event_eBooksButtonActionPerformed

    private void mAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAccountButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mAccountButtonActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void mLogOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mLogOutButtonActionPerformed
        CardLayout card = (CardLayout)MainPanel.getLayout();
        card.show(MainPanel, "WelcomePanel");
    }//GEN-LAST:event_mLogOutButtonActionPerformed

    private void eMMGoBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eMMGoBackButtonActionPerformed
        CardLayout card = (CardLayout)MainPanel.getLayout();
        card.show(MainPanel, "EmployeeHomePanel");
    }//GEN-LAST:event_eMMGoBackButtonActionPerformed

    private void eBMGoBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eBMGoBackButtonActionPerformed
        CardLayout card = (CardLayout)MainPanel.getLayout();
        card.show(MainPanel, "EmployeeHomePanel");
    }//GEN-LAST:event_eBMGoBackButtonActionPerformed

    private void jDatabaseCheckAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDatabaseCheckAction
        // TODO add your handling code here:
        DatabaseCheck check = new DatabaseCheck();
        check.setVisible(true);
        
    }//GEN-LAST:event_jDatabaseCheckAction

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BookManagementPanel;
    private javax.swing.JPanel EmployeeHomePanel;
    private javax.swing.JPanel EmployeeLogInPanel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel MemberHomePanel;
    private javax.swing.JPanel MemberLogInPanel;
    private javax.swing.JPanel MemberManagementPanel;
    private javax.swing.JPanel WelcomePanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton eBMGoBackButton;
    private javax.swing.JButton eBooksButton;
    private javax.swing.JButton eCheckOutButton;
    private javax.swing.JButton eGoBackButton;
    private javax.swing.JLabel eHomeLabel;
    private javax.swing.JButton eLogIn;
    private javax.swing.JButton eLogOutButton;
    private javax.swing.JButton eLoginButton;
    private javax.swing.JLabel eLoginTitle;
    private javax.swing.JButton eMMGoBackButton;
    private javax.swing.JButton eMembersButton;
    private javax.swing.JTextField ePasswordField;
    private javax.swing.JLabel ePasswordLabel;
    private javax.swing.JTextField eUsernameField;
    private javax.swing.JLabel eUsernameLabel;
    private javax.swing.JButton exit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel logo;
    private javax.swing.JButton mAccountButton;
    private javax.swing.JButton mCanaryButton;
    private javax.swing.JButton mGoBackButton;
    private javax.swing.JButton mLogIn;
    private javax.swing.JButton mLogOutButton;
    private javax.swing.JButton mLoginButton;
    private javax.swing.JLabel mLoginTitle;
    private javax.swing.JTextField mPasswordField;
    private javax.swing.JLabel mPasswordLabel;
    private javax.swing.JTextField mUsernameField;
    private javax.swing.JLabel mUsernameLabel;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
